# Generated by Django 6.0.6 on 2026-06-13 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('original_currency', models.CharField(default='INR', max_length=10)),
                ('expense_category', models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('utilities', 'Utilities'), ('travel', 'Travel'), ('groceries', 'Groceries'), ('entertainment', 'Entertainment'), ('settlement', 'Settlement'), ('refund', 'Refund'), ('general', 'General')], default='general', max_length=50)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV Import'), ('system', 'System')], default='manual', max_length=20)),
                ('expense_date', models.DateField()),
                ('split_type', models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('shares', 'Shares'), ('exact', 'Exact')], default='equal', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disputed', 'Disputed'), ('import_review', 'Import Review')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paid_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('expense', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('payload_json', models.JSONField(help_text='Full snapshot: expense data, participants, and splits at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='expenses.expense')),
            ],
            options={
                'ordering': ['version'],
                'unique_together': {('expense', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=4, help_text="Only for 'percentage' split type", max_digits=7, null=True)),
                ('shares_value', models.DecimalField(blank=True, decimal_places=2, help_text="Only for 'shares' split type", max_digits=10, null=True)),
                ('exact_amount', models.DecimalField(blank=True, decimal_places=2, help_text="Only for 'exact' split type", max_digits=14, null=True)),
                ('calculated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('expense', 'user')},
            },
        ),
    ]
