# Generated by Django 6.0.6 on 2026-06-14 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        ('settlements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='import_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_settlements', to='imports.importjob'),
        ),
    ]
