# Generated by Django 6.0.6 on 2026-06-14 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(max_length=50)),
                ('anomaly_category', models.CharField(choices=[('duplicate', 'Duplicate'), ('membership', 'Membership'), ('currency', 'Currency'), ('date', 'Date'), ('settlement', 'Settlement'), ('split', 'Split'), ('validation', 'Validation'), ('unknown_user', 'Unknown User')], default='validation', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('description', models.TextField()),
                ('detected_action', models.CharField(help_text='Action suggested by policy (e.g. AUTO_FIX, REVIEW_REQUIRED, REJECT)', max_length=50)),
                ('user_decision', models.CharField(blank=True, help_text='approve, reject, ignore', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('ignore', 'Ignore')], max_length=20)),
                ('decision_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anomaly', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_record', to='imports.importanomaly')),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('review_required', 'Review Required'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='groups.group')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='importanomaly',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importjob'),
        ),
        migrations.CreateModel(
            name='ImportReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_rows', models.IntegerField(default=0)),
                ('imported_rows', models.IntegerField(default=0)),
                ('skipped_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('anomaly_count', models.IntegerField(default=0)),
                ('report_json', models.JSONField(default=dict)),
                ('import_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='imports.importjob')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField(help_text='Raw CSV row as dictionary')),
                ('parsed_data', models.JSONField(blank=True, help_text='Structured representation after parsing', null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('imported', 'Imported'), ('skipped', 'Skipped'), ('review_required', 'Review Required'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importjob')),
            ],
        ),
        migrations.AddField(
            model_name='importanomaly',
            name='import_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='imports.importrow'),
        ),
    ]
