# Generated by Django 6.0.6 on 2026-06-14 21:40
# Hand-edited: add data migration step to backfill invite codes for existing groups
# before applying the unique constraint.

import secrets
import string
from django.db import migrations, models


def _generate_unique_code(existing_codes):
    """Generate a unique SPW-XXXXXXXX code not already in existing_codes."""
    chars = string.ascii_uppercase + string.digits
    while True:
        code = "SPW-" + "".join(secrets.choice(chars) for _ in range(8))
        if code not in existing_codes:
            existing_codes.add(code)
            return code


def backfill_invite_codes(apps, schema_editor):
    """Assign unique invite codes to all groups that currently have a blank code."""
    Group = apps.get_model("groups", "Group")
    existing_codes = set(
        Group.objects.exclude(invite_code="").values_list("invite_code", flat=True)
    )
    groups_to_update = Group.objects.filter(invite_code="")
    for group in groups_to_update:
        group.invite_code = _generate_unique_code(existing_codes)
    if groups_to_update:
        Group.objects.bulk_update(groups_to_update, ["invite_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        # Step 1: Add the field WITHOUT unique constraint first (allows blank during backfill)
        migrations.AddField(
            model_name='group',
            name='invite_code',
            field=models.CharField(
                blank=True,
                help_text='Unique invite code for joining this group (e.g. SPW-AB12CD34)',
                max_length=20,
                default='',
            ),
        ),

        # Step 2: Data migration — populate invite codes for all existing groups
        migrations.RunPython(backfill_invite_codes, migrations.RunPython.noop),

        # Step 3: Now apply the unique constraint (all rows have unique codes)
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(
                blank=True,
                help_text='Unique invite code for joining this group (e.g. SPW-AB12CD34)',
                max_length=20,
                unique=True,
            ),
        ),

        # Steps 4-5: Add invite audit fields to GroupMembership
        migrations.AddField(
            model_name='groupmembership',
            name='invite_code_used',
            field=models.CharField(
                blank=True,
                help_text='The invite code that was used to join, if any',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='joined_via_invite',
            field=models.BooleanField(
                default=False,
                help_text='True if this membership was created via an invite code',
            ),
        ),
    ]
